AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'webpack/**/*'
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'app/admin/**/*.rb'
    - 'config/**/*.rb'

Naming/FileName:
  Exclude:
    - 'config/initializers/rswag-api.rb'
    - 'config/initializers/rswag-ui.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/concepts/**/*.rb'

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: false

HttpPositionalArguments:
  Enabled: false

HasAndBelongsToMany:
  Enabled: false

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false
