version: '3'
services:
  postgres:
    image: postgres:9.6.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  redis:
    image: redis:4.0.0
    ports:
      - 6379:6379
