# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "auth.SignInRequest" do
    optional :username, :string, 1
    optional :password, :string, 2
  end
  add_message "auth.SignInResponse" do
    optional :auth_token, :string, 1
  end
end

module Auth
  SignInRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.SignInRequest").msgclass
  SignInResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.SignInResponse").msgclass
end
