# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: auth.proto for package 'auth'

require 'grpc'
require 'auth_pb'

module Auth
  module Session
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'auth.Session'

      rpc :sign_in, SignInRequest, SignInResponse
    end

    Stub = Service.rpc_stub_class
  end
end
