default: &default
  DEVISE_SECRET:     ''
  NO_REPLY_EMAIL:    ''
  BACKEND_HOST:      ''
  CLIENT_HOST:       ''
  MAILTRAP_USERNAME: ''
  MAILTRAP_PASSWORD: ''
  DOMAIN_NAME:       'lvh.me'
  JWT_SIGNATURE:     'test-1234'

development:
  <<: *default

test:
  <<: *default
