default: &default
  DEVISE_SECRET: ''
  SECRET_KEY_BASE: ''
  NO_REPLY_EMAIL:       ''
  HOST:                 ''
  MAILTRAP_USERNAME:    ''
  MAILTRAP_PASSWORD:    ''
  DOMAIN_NAME:          'lvh.me'
  JWT_SIGNATURE:        'test-1234'
  S3_ACCESS_KEY_ID:     ''
  S3_SECRET_ACCESS_KEY: ''
  S3_REGION:            ''
  S3_BUCKET:            ''
  FACEBOOK_KEY:         ''
  FACEBOOK_SECRET:      ''

development:
  <<: *default

test:
  <<: *default
