default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: postgres

test:
  <<: *default
  database: rg_isomorphic_test

development:
  <<: *default
  database: rg_isomorphic_dev

production:
  <<: *default
  database: rg_isomorphic
