default: &default
  adapter: postgresql
  pool: 5
  username: irdis
  password: 12345678 
test:
  <<: *default
  database: rg_isomorphic_test

development:
  <<: *default
  database: rg_isomorphic_dev
