# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fe1bf1503783fc74ed523bc35bae80e008338e8df6425874540197ef44da65e3b309d1b71d8541eae102e0d84886ab74a235e53b0ba440cbcce863a1a355a81

test:
  secret_key_base: ce25ff5d0ef734c648ed443b7c7463e2cd907bb8f3fb368a9d688948d21120ae64f700fe5fd51933203df09a76353305dde91e5f1aca99df907bb44f94b2f141

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
